SemsPLM/Controllers/QmsController.cs
using Common.Constant;
using Common.Factory;
using Common.Models;
using Common.Models.File;
using Document.Models;
using OfficeOpenXml;
using Pms.Models;
using Qms.Models;
using SemsPLM.Filter;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace SemsPLM.Controllers
{
    [AuthorizeFilter]
    public class QmsController : Controller
    {
        // GET: Qms
        public ActionResult Index()
        {
            return View();
        }

        #region -- 오픈이슈 
        public ActionResult OpenIssueList()
        {
            return View();
        }

        public ActionResult InfoOpenIssue(int? OID)
        {
            if (OID == null) { throw new Exception(""); }

            OpenIssue _OpenIssue = OpenIssueRepository.SelOpenIssue(new OpenIssue() { OID = OID });
            ViewBag.OpenIssue = _OpenIssue;
            ViewBag.Status = BPolicyRepository.SelBPolicy(new BPolicy { Type = QmsConstant.TYPE_OPEN_ISSUE });
            ViewBag.ItemStatus = BPolicyRepository.SelBPolicy(new BPolicy { Type = QmsConstant.TYPE_OPEN_ISSUE_ITEM });

            var items = OpenIssueItemRepository.SelOpenIssueItems(new OpenIssueItem() { OpenIssueOID = OID });
            ViewBag.OpenIssueItemCnt = items == null ? 0 : items.Count();

            if (items == null)
            {
                ViewBag.ItemRatio = null;
            }
            else if (items.Count() > 0)
            {
                int FinishCnt = _OpenIssue.CompleatedCnt;

                ViewBag.ItemRatio = (FinishCnt / items.Count() * 100).ToString() + "%";
            }

            return View();
        }

        public ActionResult EditOpenIssue(OpenIssue _param)
        {
            ViewBag.OpenIssueOID = _param.OID;
            return View("Dialog/dlgEditOpenIssue", _param);
        }

        public JsonResult SelOpenIssue(OpenIssue _param)
        {
            return Json(OpenIssueRepository.SelOpenIssue(_param));
        }

        public JsonResult SelOpenIssues(OpenIssue _param)
        {
            return Json(OpenIssueRepository.SelOpenIssues(_param));
        }

        public JsonResult SelOpenIssueItems(OpenIssueItem _param)
        {
            return Json(OpenIssueItemRepository.SelOpenIssueItems(_param));
        }

        public JsonResult InsOpenIssue(OpenIssue _param, List<OpenIssueItem> openIssueItems, List<QuickResponse> quickResponses)
        {
            int resultValue = 0;
            try
            {
                DaoFactory.BeginTransaction();

                OpenIssue openIssue = new OpenIssue()
                {
                    CustomerLibOID = _param.CustomerLibOID,
                    CarLibOID = _param.CarLibOID,
                    ProjectOID = _param.ProjectOID,
                };

                // OpenIssue 신규작성 일 경우 OpenIssue OID 생성
                if (openIssue.OID == null)
                {
                    DObject dobj = new DObject();
                    dobj.Type = QmsConstant.TYPE_OPEN_ISSUE;
                    dobj.Name = QmsConstant.TYPE_OPEN_ISSUE;
                    openIssue.OID = DObjectRepository.InsDObject(Session, dobj);

                    resultValue = OpenIssueRepository.InsOpenIssue(openIssue);
                }

                // OpenIssue 리스트 항목 추가
                if (openIssueItems.Count > 0)
                {
                    OpenIssueRelationship openIssueRelationship = null;
                    openIssueItems.ForEach(item =>
                    {
                        OpenIssueItem openIssueItem = new OpenIssueItem()
                        {
                            RelapseInsideFl = item.RelapseInsideFl,
                            RelapseHanonFl = item.RelapseHanonFl,
                            RelapseCarFl = item.RelapseCarFl,
                            OpenIssueDetailDesc = item.OpenIssueDetailDesc,
                            OpenIssueOccurrenceDt = item.OpenIssueOccurrenceDt,
                            OpenIssueExpectedDt = item.OpenIssueExpectedDt,
                            OpenIssueCompleteDt = item.OpenIssueCompleteDt,
                            OpenIssueCloseFl = item.OpenIssueCloseFl
                        };

                        if (openIssue.OID == null)
                        {
                            DObject dobj = new DObject();
                            dobj.Type = QmsConstant.TYPE_OPEN_ISSUE_ITEM;
                            dobj.Name = QmsConstant.TYPE_OPEN_ISSUE_ITEM + "_" + openIssue.OID;
                            dobj.BPolicyOID = _param.BPolicyOID;
                            openIssueItem.OID = DObjectRepository.InsDObject(Session, dobj);

                            resultValue = OpenIssueItemRepository.InsOpenIssueItem(openIssueItem);
                        }

                        if (openIssueRelationship != null)
                        {
                            openIssueRelationship = null;
                        }

                        // OpenIssue 와 OpenIssue 리스트 항목 릴레이션 연결
                        openIssueRelationship = new OpenIssueRelationship()
                        {
                            FromOID = openIssue.OID,
                            ToOID = openIssueItem.OID,
                            type = QmsConstant.TYPE_OPEN_ISSUE_ITEM,
                            CreateUs = Convert.ToInt32(Session["UserOID"])
                        };

                        resultValue = OpenIssueRelationshipRepository.InsOpenIssueRelationship(openIssueRelationship);
                    });
                }

                // 신속대응 연결
                if (quickResponses.Count > 0)
                {
                    OpenIssueRelationship openIssueRelationship = null;
                    quickResponses.ForEach(item =>
                    {
                        if (openIssueRelationship != null)
                        {
                            openIssueRelationship = null;
                        }

                        openIssueRelationship = new OpenIssueRelationship()
                        {
                            FromOID = openIssue.OID,
                            ToOID = item.OID,
                            type = QmsConstant.TYPE_QUICK_RESPONSE,
                            CreateUs = Convert.ToInt32(Session["UserOID"])
                        };

                        resultValue = OpenIssueRelationshipRepository.InsOpenIssueRelationship(openIssueRelationship);
                    });
                }

                DaoFactory.Commit();
                return Json(1);
            }
            catch (Exception ex)
            {
                DaoFactory.Rollback();
                return Json(new ResultJsonModel { isError = true, resultMessage = ex.Message, resultDescription = ex.ToString() });
            }
        }

        public JsonResult SaveOpenIssueItem(OpenIssue _param)
        {
            try
            {
                DaoFactory.BeginTransaction();

                // OpenIssue 리스트 항목 추가
                if (_param.OpenIssueItems != null && _param.OpenIssueItems.Count > 0)
                {

                    _param.OpenIssueItems.ForEach(item =>
                    {
                        int? ItemOID = null;
                        OpenIssueItem openIssueItem = new OpenIssueItem()
                        {
                            OpenIssueTitle = item.OpenIssueTitle,
                            RelapseInsideFl = item.RelapseInsideFl,
                            RelapseHanonFl = item.RelapseHanonFl,
                            RelapseCarFl = item.RelapseCarFl,
                            OpenIssueDetailDesc = item.OpenIssueDetailDesc,
                            OpenIssueOccurrenceDt = item.OpenIssueOccurrenceDt,
                            OpenIssueExpectedDt = item.OpenIssueExpectedDt,
                            OpenIssueCompleteDt = item.OpenIssueCompleteDt,
                            OpenIssueCloseFl = item.OpenIssueCloseFl
                        };

                        if (item.OID == null)
                        {
                            if (item.IsDel == "Y")
                            {
                                return;
                            }

                            _param.BPolicyOID = null;

                            DObject dobj = new DObject();
                            dobj.Type = QmsConstant.TYPE_OPEN_ISSUE_ITEM;
                            dobj.Name = QmsConstant.TYPE_OPEN_ISSUE_ITEM + "_" + _param.OID;
                            dobj.Description = _param.Description;
                            ItemOID = DObjectRepository.InsDObject(Session, dobj);
                            openIssueItem.OID = ItemOID;
                            OpenIssueItemRepository.InsOpenIssueItem(openIssueItem);

                            OpenIssueRelationship openIssueRelationship = new OpenIssueRelationship()
                            {
                                FromOID = _param.OID,
                                ToOID = ItemOID,
                                type = QmsConstant.TYPE_OPEN_ISSUE_ITEM,
                                CreateUs = Convert.ToInt32(Session["UserOID"])
                            };

                            OpenIssueRelationshipRepository.InsOpenIssueRelationship(openIssueRelationship);

                            OpenIssueRepository.UdtOpenIssueSuspenseCnt(_param);
                        }
                        else
                        {
                            if (item.IsDel == "Y")
                            {
                                var policys = BPolicyRepository.SelBPolicy(new BPolicy { Type = QmsConstant.TYPE_OPEN_ISSUE_ITEM });

                                policys.ForEach(v =>
                                {
                                    if (item.BPolicyOID == v.OID)
                                    {

SemsPLM/Views/Qms/Dialog/dlgEditQuickBlockade.cshtml
@{
    Layout = null;
}

    <div class="qmsDlgTable">
        <div style="width:100%;text-align:right;padding-right:10px;position:relative;">
            <button id="btnDlgSave" onclick="" class="custom-button"><i class="fas fa-save"></i> 저장</button>
            <button id="btnDlgConfirm" onclick="" class="custom-button"><i class="fas fa-check-circle"></i> 결재</button>
        </div>

        @{Html.RenderAction("QuickResponseSummary", "Qms", new { OID = ViewBag.QuickOID });}
        <label><i class="fas fa-toolbox"></i> 봉쇄조치</label>
        <table id="tbBlockadeList" class="infoTable" style="table-layout:fixed;">
            <colgroup>
                <col style="width:9%" />
                <col style="width:18%" />
                <col style="width:18%" />
                <col style="width:9%" />
                <col style="width:16%" />
                <col style="width:13%" />
                <col style="width:30%" />
            </colgroup>
            <tr>
                <th>범위</th>
                <th>대상범위</th>
                <th>조치방법</th>
                <th>대상수량</th>
                <th>조치부서</th>
                <th>담당자</th>
                <th>기한</th>
            </tr>
        </table>

        <label>시정</label>
        <table id="tbCorrectiveAction" class="infoTable" style="table-layout:fixed;">
            <colgroup>
                <col style="width:9%" />
                <col style="width:11%" />
                <col style="width:11%" />
                <col style="width:11%" />
                <col style="width:11%" />
                <col style="width:11%" />
                <col style="width:11%" />
                <col style="width:25%" />
            </colgroup>
            <tr>
                <th rowspan="2">범위</th>
                <th colspan="2">선별</th>
                <th rowspan="2">재작업</th>
                <th rowspan="2">폐기</th>
                <th rowspan="2">특채</th>
                <th rowspan="2">기타</th>
                <th rowspan="2">비고</th>
            </tr>
            <tr>
                <th>적합</th>
                <th>부적합</th>
            </tr>
        </table>

    </div>

<script type="text/javascript">
    $(document).ready(function () {
        var BlockadeList = @Html.Raw(Json.Encode(Model));

        BlockadeList.forEach(function (v, i) {
            PrintBlockade(v);
            PrintCorrectiveAction(v);
        });

        $("#btnDlgSave").on("click", function () {
            SaveBlockade();
        });
    });

    function PrintBlockade(v) {
        var tr$ = document.createElement("tr");
        tr$.setAttribute("BlockadeType", v.Type);
        tr$.setAttribute("OID", v.OID);
        tr$.setAttribute("Data", "Y");
        var tdType$ = document.createElement("td");
        var lbType$ = document.createElement("label");
        lbType$.innerText = v.Name;
        tdType$.appendChild(lbType$);

        var tdTargetScope$ = document.createElement("td");
        var txtTargetScope$ = document.createElement("input");
        txtTargetScope$.setAttribute("name", "TargetScope");
        txtTargetScope$.setAttribute("type", "text");
        txtTargetScope$.style.width = "100%";
        txtTargetScope$.value = v.TargetScope;
        txtTargetScope$.className = "txtBox";            
        tdTargetScope$.appendChild(txtTargetScope$);

        var tdAct$ = document.createElement("td");
        var txtAct$ = document.createElement("input");
        txtAct$.setAttribute("type", "text");
        txtAct$.setAttribute("name", "Act");
        txtAct$.style.width = "100%";
        txtAct$.value = v.Act;
        txtAct$.className = "txtBox";            
        tdAct$.appendChild(txtAct$);

        var tdTargetCnt$ = document.createElement("td");
        var txtTargetCnt$ = document.createElement("input");
        txtTargetCnt$.setAttribute("type", "text");
        txtTargetCnt$.setAttribute("name", "TargetCnt");
        txtTargetCnt$.style.width = "100%";
        txtTargetCnt$.value = v.TargetCnt;
        txtTargetCnt$.className = "txtBox";            
        tdTargetCnt$.appendChild(txtTargetCnt$);

        // 사용자하고 부서 선택해야함.
        var tdActDepartmentOID = document.createElement("td");
        tdActDepartmentOID.innerText = v.ActDepartmentNm;
        var tdActUserOID$ = document.createElement("td");
        tdActUserOID$.innerText = v.ActUserNm;

        var tdActDt$ = document.createElement("td");
        var divActDt$ = document.createElement("div");
        divActDt$.style.display = "flex";
        divActDt$.style.flexDirection = "row";
        var txtActStartDt$ = document.createElement("div");
        txtActStartDt$.setAttribute("name", "ActStartDt");
        $(txtActStartDt$).jqxDateTimeInput(DateFormat);
        $(txtActStartDt$).jqxDateTimeInput({
            width: 140,
            height:30,
            theme: "Light"
        });   
        if (v.ActStartDt === null) {
            $(txtActStartDt$).val(WebUtils.GetDate(0, "d", "-"));
        } else {
            var milli = v.ActStartDt.replace(/\/Date\((-?\d+)\)\//, '$1');
            var d = new Date(parseInt(milli));
            $(txtActStartDt$).val(d.getFullYear() + "-" + (d.getMonth() + 1) + "-" + d.getDate());
        }

        var txtActEndDt$ = document.createElement("div");
        txtActEndDt$.setAttribute("name", "ActEndDt");
        $(txtActEndDt$).jqxDateTimeInput(DateFormat);
        $(txtActEndDt$).jqxDateTimeInput({
            width: 140,
            height:30,
            theme: "Light"
        });   
        if (v.ActEndDt === null) {
            $(txtActEndDt$).val(WebUtils.GetDate(0, "d", "-"));
        } else {
            var milli = v.ActEndDt.replace(/\/Date\((-?\d+)\)\//, '$1');
            var d = new Date(parseInt(milli));
            $(txtActEndDt$).val(d.getFullYear() + "-" + (d.getMonth() + 1) + "-" + d.getDate());
        }

        var lbActDtRange$ = document.createElement("label");
        lbActDtRange$.innerText = "~";
            
        divActDt$.appendChild(txtActStartDt$);
        divActDt$.appendChild(lbActDtRange$);
        divActDt$.appendChild(txtActEndDt$);
        tdActDt$.appendChild(divActDt$);

        tr$.appendChild(tdType$);
        tr$.appendChild(tdTargetScope$);
        tr$.appendChild(tdAct$);
        tr$.appendChild(tdTargetCnt$);
        tr$.appendChild(tdActDepartmentOID);
        tr$.appendChild(tdActUserOID$);
        tr$.appendChild(tdActDt$);

        document.getElementById("tbBlockadeList").appendChild(tr$);
    }

    function PrintCorrectiveAction(v) {
        var tr$ = document.createElement("tr");
        tr$.setAttribute("BlockadeType", v.Type);
        tr$.setAttribute("OID", v.OID);

        var tdType$ = document.createElement("td");
        var lbType$ = document.createElement("label");
        lbType$.innerText = v.Name;
        tdType$.appendChild(lbType$);
        
        var tdSortSuitableCnt$ = document.createElement("td");
        var txtSortSuitableCnt$ = document.createElement("input");
        txtSortSuitableCnt$.setAttribute("type", "text");
        txtSortSuitableCnt$.setAttribute("name", "SortSuitableCnt");
        txtSortSuitableCnt$.style.width = "100%";
        txtSortSuitableCnt$.value = v.SortSuitableCnt;
        txtSortSuitableCnt$.className = "txtBox";            
        tdSortSuitableCnt$.appendChild(txtSortSuitableCnt$);

        var tdSortIncongruityCnt$ = document.createElement("td");
        var txtSortIncongruityCnt$ = document.createElement("input");
        txtSortIncongruityCnt$.setAttribute("type", "text");
        txtSortIncongruityCnt$.setAttribute("name", "SortIncongruityCnt");
        txtSortIncongruityCnt$.style.width = "100%";
        txtSortIncongruityCnt$.value = v.SortIncongruityCnt;
        txtSortIncongruityCnt$.className = "txtBox";            
        tdSortIncongruityCnt$.appendChild(txtSortIncongruityCnt$);

        var tdReworkCnt$ = document.createElement("td");
        var txtReworkCnt$ = document.createElement("input");
        txtReworkCnt$.setAttribute("type", "text");
        txtReworkCnt$.setAttribute("name", "ReworkCnt");
        txtReworkCnt$.style.width = "100%";
        txtReworkCnt$.value = v.ReworkCnt;
        txtReworkCnt$.className = "txtBox";            
        tdReworkCnt$.appendChild(txtReworkCnt$);

        var tdDisuseCnt$ = document.createElement("td");
        var txtDisuseCnt$ = document.createElement("input");
        txtDisuseCnt$.setAttribute("type", "text");
        txtDisuseCnt$.setAttribute("name", "DisuseCnt");
        txtDisuseCnt$.style.width = "100%";
        txtDisuseCnt$.value = v.DisuseCnt;
        txtDisuseCnt$.className = "txtBox";            
        tdDisuseCnt$.appendChild(txtDisuseCnt$);

        var tdSpecialCnt$ = document.createElement("td");
        var txtSpecialCnt$ = document.createElement("input");
        txtSpecialCnt$.setAttribute("type", "text");
        txtSpecialCnt$.setAttribute("name", "SpecialCnt");
        txtSpecialCnt$.style.width = "100%";
        txtSpecialCnt$.value = v.SpecialCnt;
        txtSpecialCnt$.className = "txtBox";            
        tdSpecialCnt$.appendChild(txtSpecialCnt$);

        var tdEtcCnt$ = document.createElement("td");
        var txtEtcCnt$ = document.createElement("input");
        txtEtcCnt$.setAttribute("type", "text");
        txtEtcCnt$.setAttribute("name", "EtcCnt");
        txtEtcCnt$.style.width = "100%";
        txtEtcCnt$.value = v.EtcCnt;
        txtEtcCnt$.className = "txtBox";            
        tdEtcCnt$.appendChild(txtEtcCnt$);

        var tdDesc$ = document.createElement("td");
        var txtDesc$ = document.createElement("input");
        txtDesc$.setAttribute("type", "text");
        txtDesc$.setAttribute("name", "Description");
        txtDesc$.style.width = "100%";
        txtDesc$.value = v.Description;
        txtDesc$.className = "txtBox";            
        tdDesc$.appendChild(txtDesc$);

        tr$.appendChild(tdType$);
        tr$.appendChild(tdSortSuitableCnt$);
        tr$.appendChild(tdSortIncongruityCnt$);
        tr$.appendChild(tdReworkCnt$);
        tr$.appendChild(tdDisuseCnt$);
        tr$.appendChild(tdSpecialCnt$);
        tr$.appendChild(tdEtcCnt$);
        tr$.appendChild(tdDesc$);

        document.getElementById("tbCorrectiveAction").appendChild(tr$);
    }

    function SaveBlockade() {
        var params = [];
        var tr$ = $("#tbBlockadeList tr[Data='Y']");
        
        tr$.each(function (i, v) {           
            var param = {};
            param.OID = $(v).attr("OID");
            param.TargetScope = $($(v).find("[name='TargetScope']")[0]).val();
            param.Act =  $($(v).find("[name='Act']")[0]).val();
            param.TargetCnt =  $($(v).find("[name='TargetCnt']")[0]).val();
            param.ActDepartmentOID = 70; //$($(v).find("[name='ActDepartmentOID']")[0]).val();
            param.ActUserOID = 75; //$($(v).find("[name='ActUserOID']")[0]).val();
            param.ActStartDt =  $($(v).find("[name='ActStartDt']")[0]).val();
            param.ActEndDt = $($(v).find("[name='ActEndDt']")[0]).val();

            var trCorrectiveAction$ = $("#tbCorrectiveAction").children("[OID='" + param.OID + "']")[0];

            param.SortSuitableCnt =  $($(trCorrectiveAction$).find("[name='SortSuitableCnt']")[0]).val();
            param.SortIncongruityCnt =  $($(trCorrectiveAction$).find("[name='SortIncongruityCnt']")[0]).val();
            param.ReworkCnt =  $($(trCorrectiveAction$).find("[name='ReworkCnt']")[0]).val();
            param.DisuseCnt =  $($(trCorrectiveAction$).find("[name='DisuseCnt']")[0]).val();
            param.SpecialCnt =  $($(trCorrectiveAction$).find("[name='SpecialCnt']")[0]).val();
            param.EtcCnt =  $($(trCorrectiveAction$).find("[name='EtcCnt']")[0]).val();
            param.Description = $($(trCorrectiveAction$).find("[name='Description']")[0]).val();

            params.push(param);
        });

        $.post('/Qms/SaveQuickBlockade', { _params: params }, function (response) {
            if (response.isError) {
                alert(response.resultMessage);
                return;
            }
            alert("저장되었습니다.");
        }).fail(function (err) {
            alert(err.responseText);
        });
    }
</script>

SemsPLM/Views/Qms/Dialog/dlgEditQuickImproveCounterMeasure.cshtml
@{
    Layout = null;
}

    <div class="qmsDlgTable">
        <div style="width:100%;text-align:right;padding-right:10px;position:relative;">
            <button id="btnDlgSave" onclick="" class="custom-button"><i class="fas fa-check-circle"></i> 저장</button>
            <button id="btnDlgConfirm" onclick="" class="custom-button"><i class="fas fa-check-circle"></i> 결재</button>
        </div>

        @{Html.RenderAction("QuickResponseSummary", "Qms", new { OID = ViewBag.QuickOID });}

        <label><i class="fas fa-toolbox"></i> 근본원인 개선대책</label>
        <table id="tbImproveCounterMeasure" class="infoTable" style="table-layout:fixed;">
            <colgroup>
                <col style="width:37%" />
                <col style="width:37%" />
                <col style="width:15%" />
                <col style="width:11%" />
            </colgroup>
            <tr>
                <th>근본원인</th>
                <th>개선대책</th>
                <th>처리일자</th>
                <th><button id="btnImproveCounterMeasureAdd">원인추가</button></th>
            </tr>
        </table>
    </div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnDlgSave").jqxButton();
        $("#btnDlgSave").on("click", function () {
            SaveImproveCounterMeasure();
        })

        $("#btnImproveCounterMeasureAdd").jqxButton();
        $("#btnImproveCounterMeasureAdd").on("click", function () {
            AddImproveCounterMeasureAdd(null);
        });

        var ImproveCounterMeasures = @Html.Raw(Json.Encode(ViewBag.ImproveCounterMeasures));

        if (ImproveCounterMeasures.length === 0) {
            AddImproveCounterMeasureAdd(null);
        } else {
            ImproveCounterMeasures.forEach(function (v, i) {
                AddImproveCounterMeasureAdd(v);
            });
        }
    });

    function AddImproveCounterMeasureAdd(data) {
        var OID = data == null ? null : data.OID;
        var table$ = document.getElementById("tbImproveCounterMeasure");

        var tr$ = document.createElement("tr");
        tr$.setAttribute("Data", "Y");
        tr$.setAttribute("OID", OID);

        var tdRootCause$ = document.createElement("td");
        var txtRootCause$ = document.createElement("input");
        txtRootCause$.setAttribute("type", "text");
        txtRootCause$.setAttribute("name", "RootCause");
        txtRootCause$.style.width = "100%";
        if (data !== null) {
            txtRootCause$.value = data.RootCause;
        }        
        txtRootCause$.className = "txtBox";            
        tdRootCause$.appendChild(txtRootCause$);

        var tdImproveCountermeasure$ = document.createElement("td");
        var txtImproveCountermeasure$ = document.createElement("input");
        txtImproveCountermeasure$.setAttribute("type", "text");
        txtImproveCountermeasure$.setAttribute("name", "ImproveCountermeasure");
        txtImproveCountermeasure$.style.width = "100%";
         if (data !== null) {
            txtImproveCountermeasure$.value = data.ImproveCountermeasure;
        }     
        txtImproveCountermeasure$.className = "txtBox";            
        tdImproveCountermeasure$.appendChild(txtImproveCountermeasure$);

        var tdProcessDt$ = document.createElement("td");
        var dtProcessDt$ = document.createElement("div");
        dtProcessDt$.setAttribute("name", "ProcessDt");
        $(dtProcessDt$).jqxDateTimeInput(DateFormat);
        $(dtProcessDt$).jqxDateTimeInput({
            width: 140,
            height:30,
            theme: "Light"
        });
        if (data === null) {
            $(dtProcessDt$).val(WebUtils.GetDate(0, "d", "-"));
        } else {
            var milli = data.ProcessDt.replace(/\/Date\((-?\d+)\)\//, '$1');
            var d = new Date(parseInt(milli));
            $(dtProcessDt$).val(d.getFullYear() + "-" + (d.getMonth() + 1) + "-" + d.getDate());
        }

        tdProcessDt$.appendChild(dtProcessDt$);

        var tdBtn$ = document.createElement("td");
        var btnDel = document.createElement("button");
        btnDel.innerText = "행 삭제";
        tdBtn$.appendChild(btnDel);
        $(btnDel).jqxButton();

        $(btnDel).on("click", function () {
            tr$.setAttribute("Remove", "Y");
            tr$.style.display = "none";
        });
        
        tr$.appendChild(tdRootCause$);
        tr$.appendChild(tdImproveCountermeasure$);
        tr$.appendChild(tdProcessDt$);
        tr$.appendChild(tdBtn$);

        table$.appendChild(tr$);
    }

    function SaveImproveCounterMeasure() {
        var params = [];
        var trImproveCounterMeasure$ = $("#tbImproveCounterMeasure tr[Data='Y']");
        var errMsg = "";

        trImproveCounterMeasure$.each(function (i, v) {
            var data = {};
            data.OID = $(v).attr("OID") === "null" ? null : $(v).attr("OID");
            data.ModuleOID = "@ViewBag.ModuleOID";
            data.RootCause = $($(v).find("[name='RootCause']")[0]).val();
            data.ImproveCountermeasure = $($(v).find("[name='ImproveCountermeasure']")[0]).val();
            data.ProcessDt = $($(v).find("[name='ProcessDt']")[0]).val();

            if ($(v).attr("Remove") === "Y") {
                data.IsRemove = "Y";
            }

            if (WebUtils.isBlank(data.RootCause)) {
                errMsg += "[" + (i + 1).toString() + "] 행의 근본원인이 입력되지 않았습니다.\n";
            }

            if (WebUtils.isBlank(data.ImproveCountermeasure)) {
                errMsg += "[" + (i + 1).toString() + "] 행의 개선대책이 입력되지 않았습니다.\n";
            }

            if (WebUtils.isBlank(data.ProcessDt)) {
                errMsg += "[" + (i + 1).toString() + "] 행의 처리일자가 입력되지 않았습니다.\n";
            }

            params.push(data);
        });

        if (errMsg.length != 0) {
            alert(errMsg); return;
        }

        $.post('/Qms/SavetQuickImproveCounterMeasure', { _params: params }, function (response) {
            if (response.isError) {
                alert(response.resultMessage);
                return;
            }
            alert("저장되었습니다.");
        }).fail(function (err) {
            alert(err.responseText);
        });
    }
</script>