SemsPLM/Controllers/CommonController.cs
using Common;
using Common.Constant;
using Common.Factory;
using Common.Models;
using Common.Models.File;
using Common.Utils;
using SemsPLM.Filter;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using Trigger;

namespace SemsPLM.Controllers
{
    [AuthorizeFilter]
    public class CommonController : Controller
    {
        // GET: Common

        #region -- Menu

        public ActionResult Menu()
        {

            ViewBag.Menu = BMenuRepository.SelBMenu();
            return PartialView("Partitial/ptMenu");
        }

        #endregion

        #region -- Person

        public ActionResult ApprovalPerson()
        {
            ViewBag.Organization = CompanyRepository.SelOrganizationWithPerson(Session, new List<string> { CommonConstant.TYPE_PERSON });
            //ViewBag.Organization = CompanyRepository.SelOrganizationWithPerson(null);
            return PartialView("Dialog/dlgApprovalPerson");
        }

        #endregion

        #region -- My Approval

        public ActionResult MyApproval()
        {
            ViewBag.Types = BDefineRepository.SelDefines(new BDefine { Type = CommonConstant.DEFINE_TYPE });
            ViewBag.Status = BPolicyRepository.SelBPolicy(new BPolicy { Type = CommonConstant.TYPE_APPROVAL_TASK });
            return View();
        }

        public JsonResult SelMyApproval(ApprovalTask _param)
        {
            List<ApprovalTask> myApproval = new List<ApprovalTask>();
            ApprovalTaskRepository.SelInboxMyTasks(Session, _param).ForEach(approv =>
            {
                approv.ApprovalBPolicy = DObjectRepository.SelDObject(Session, new DObject { OID = approv.ApprovalOID }).BPolicy;
                if (approv.BPolicy.Name == approv.ApprovalBPolicy.Name)
                {
                    myApproval.Add(approv);
                }
            });
            return Json(myApproval);
        }

        public JsonResult PromoteApprovalTask(ApprovalTask _param)
        {
            try
            {
                DaoFactory.BeginTransaction();
                ApprovalTaskRepository.UdtInboxTask(new ApprovalTask { ActionType = _param.ActionType, Comment = _param.Comment, OID = _param.OID });
                TriggerUtil.StatusPromote(Session, false, CommonConstant.TYPE_APPROVAL_TASK, Convert.ToString(_param.BPolicyOID), Convert.ToInt32(_param.OID), Convert.ToInt32(_param.OID), _param.ActionType, "");
                
                if (_param.ActionType == CommonConstant.ACTION_REJECT)
                {
                    Approval tmpApproval = ApprovalRepository.SelApprovalNonStep(Session, new Approval { OID = _param.ApprovalOID });
                    string returnVal = TriggerUtil.StatusPromote(Session, false, CommonConstant.TYPE_APPROVAL, Convert.ToString(tmpApproval.BPolicyOID), Convert.ToInt32(tmpApproval.OID), Convert.ToInt32(tmpApproval.OID), _param.ActionType, "");
                    if (returnVal != null && returnVal.Length > 0)
                    {
                        throw new Exception(returnVal);
                    }

                    returnVal = "";
                    DObject targetDobj = DObjectRepository.SelDObject(Session, new DObject { OID = tmpApproval.TargetOID });
                    returnVal = TriggerUtil.StatusPromote(Session, false, targetDobj.Type, Convert.ToString(targetDobj.BPolicyOID), Convert.ToInt32(targetDobj.OID), Convert.ToInt32(targetDobj.OID), _param.ActionType, "");
                    if (returnVal != null && returnVal.Length > 0)
                    {
                        throw new Exception(returnVal);
                    }
                    DaoFactory.Commit();
                    return Json(CommonConstant.RETURN_SUCCESS);
                }

                bool allSuccess = true;
                ApprovalStep tmpApprovalStep = ApprovalStepRepository.SelApprovalStep(Session, new ApprovalStep { OID = _param.StepOID });
                tmpApprovalStep.InboxTask.ForEach(task =>
                {
                    if (task.BPolicy.Name != CommonConstant.POLICY_APPROVAL_COMPLETED)
                    {
                        allSuccess = false;
                    }
                });

                if (allSuccess)
                {
                   Approval tmpApproval = ApprovalRepository.SelApprovalNonStep(Session, new Approval { OID = _param.ApprovalOID });
                   int cntCurrent = Convert.ToInt32(tmpApproval.CurrentNum);
                   cntCurrent += 1;
                   if (tmpApproval.ApprovalCount >= cntCurrent)
                   {
                        string returnVal = "";
                        ApprovalRepository.UdtApproval(Session, new Approval { CurrentNum = cntCurrent, OID = tmpApproval.OID });
                        ApprovalRepository.SelApproval(Session, new Approval { OID = tmpApproval.OID }).InboxStep.Find(step => step.Ord == cntCurrent).InboxTask.ForEach(task =>
                        {
                            returnVal = "";
                            returnVal = TriggerUtil.StatusPromote(Session, false, CommonConstant.TYPE_APPROVAL_TASK, Convert.ToString(task.BPolicyOID), Convert.ToInt32(task.OID), Convert.ToInt32(task.OID), _param.ActionType, "");
                            if (returnVal != null && returnVal.Length > 0)
                            {
                                throw new Exception(returnVal);
                            }
                        });
                   }
                   else if (tmpApproval.ApprovalCount < cntCurrent)
                   {
                        string returnVal = "";
                        ApprovalRepository.UdtApproval(Session, new Approval { CurrentNum = cntCurrent, OID = tmpApproval.OID });
                        returnVal = TriggerUtil.StatusPromote(Session, false, CommonConstant.TYPE_APPROVAL, Convert.ToString(tmpApproval.BPolicyOID), Convert.ToInt32(tmpApproval.OID), Convert.ToInt32(tmpApproval.OID), _param.ActionType, "");
                        if (returnVal != null && returnVal.Length > 0)
                        {
                            throw new Exception(returnVal);
                        }

                        returnVal = "";
                        DObject targetDobj = DObjectRepository.SelDObject(Session, new DObject { OID = tmpApproval.TargetOID });
                        returnVal = TriggerUtil.StatusPromote(Session, false, targetDobj.Type, Convert.ToString(targetDobj.BPolicyOID), Convert.ToInt32(targetDobj.OID), Convert.ToInt32(targetDobj.OID), _param.ActionType, "");
                        if (returnVal != null && returnVal.Length > 0)
                        {
                            throw new Exception(returnVal);
                        }
                    }
                }
                DaoFactory.Commit();
            }
            catch(Exception ex)
            {
                DaoFactory.Rollback();
                return Json(new ResultJsonModel { isError = true, resultMessage = ex.Message, resultDescription = ex.ToString() });
            }
            return Json(CommonConstant.RETURN_SUCCESS);
        }

        public JsonResult PromoteObjectTask(string Type, string OID, string RootOID, string Status, string GoStatusOID, string Action, string Comment)
        {
            try
            {
                DaoFactory.BeginTransaction();

                string returnVal = "";
                DObject targetDobj = DObjectRepository.SelDObject(Session, new DObject { OID = Convert.ToInt32(OID) });
                returnVal = TriggerUtil.StatusObjectPromote(Session, false, targetDobj.Type, Convert.ToString(targetDobj.BPolicyOID), GoStatusOID, Convert.ToInt32(targetDobj.OID), (RootOID == null ? Convert.ToInt32(targetDobj.OID) : Convert.ToInt32(RootOID)), Action, "");
                if (returnVal != null && returnVal.Length > 0)
                {
                    throw new Exception(returnVal);
                }
                DaoFactory.Commit();
            }
            catch (Exception ex)
            {
                DaoFactory.Rollback();
                return Json(new ResultJsonModel { isError = true, resultMessage = ex.Message, resultDescription = ex.ToString() });
            }
            return Json(CommonConstant.RETURN_SUCCESS);
        }

        #endregion

        #region -- Approval

        public ActionResult Approval(Approval _param)
        {
            ViewBag.Organization = CompanyRepository.SelOrganizationWithPerson(Session, new List<string> { CommonConstant.TYPE_PERSON });
            if (_param.TargetOID != null)
            {
                ViewBag.TargetOID = _param.TargetOID;
            }
            ViewBag.SelApproval = ApprovalRepository.SelSaveApprovalsNonStep(Session, new Approval{Type = Common.Constant.CommonConstant.TYPE_SAVE_APPROVAL });
            return PartialView("Dialog/dlgApproval");
        }

        public JsonResult SelApproval(Approval _param)
        {
            if(_param.OID == null)
            {
                return Json(ApprovalRepository.SelApprovals(Session, _param));
            }
            return Json(null);
        }

        public JsonResult InsApproval(Approval _param)
        {
            int result = 0;
            try
            {
                DaoFactory.BeginTransaction();
                
                DObject dobj = new DObject();
                if (_param.TargetOID == null)
                {
                    dobj.Type = CommonConstant.TYPE_SAVE_APPROVAL;
                    dobj.Name = _param.Name;
                }
                else
                {
                    dobj.Type = CommonConstant.TYPE_APPROVAL;
                    string strApprovalPrefix = dobj.Type + "-" + DateTime.Now.ToString("yyyyMMdd") + "-";

SemsPLM/Views/Qms/InfoErrorProof.cshtml
@{
    Layout = null;
}

    <div id="InfoErrorProof_@ViewBag.ErrorProof.OID" class="info_project clearfix">
        <div class="info_menubar">
            <ul>
                <li class="tab info_focus" info="properties"><i class="fas fa-info-circle"></i> 기본 정보</li>
                <li class="tab" info="Apphis"><i class="fas fa-stream"></i> 결재이력</li>
                <li class="tab" info="Downhis"><i class="fas fa-users"></i> 다운로드 이력</li>
            </ul>
        </div>
        <div class="doc_content">
            <div class="project_basic clearfix">
                <div class="basic_info">
                    <h3>Errof Proof</h3>
                    <p>제 목 : <span>@ViewBag.QuickDetail.Title</span></p>
                </div>
                <div class="basic_image">
                    <div class="image_inputbox">이미지<!--이미지 드래그 영역--></div>
                    <div class="image_thumbnail"><!--이미지 썸네일 영역--></div>
                </div>
                <div class="basic_status">
                    <div class="pointer_wrap">
                        @for (int i = 0; i < ViewBag.Status.Count; i++)
                        {
                            if (ViewBag.ErrorProof.BPolicyOID == ViewBag.Status[i].StatusOID)
                            {
                                <div class="pointer pointer_focus" data-type="@ViewBag.Status[i].Type" data-Status="@ViewBag.Status[i].StatusOID" style="z-index: @(ViewBag.Status.Count - i);">
                                    <div class="project_status">@ViewBag.Status[i].StatusNm</div>
                                </div>
                            }
                            else
                            {
                                <div class="pointer" data-type="@ViewBag.Status[i].Type" data-Status="@ViewBag.Status[i].StatusOID" style="z-index: @(ViewBag.Status.Count - i);">
                                    <div class="project_status">@ViewBag.Status[i].StatusNm</div>
                                </div>
                            }
                        }
                    </div>
                    <p>설명 : <span></span></p>
                </div>
            </div>
            <div id="properties" class="basic_grid">
                @if ((ViewBag.ErrorProof.BPolicyNm == Common.Constant.QmsConstant.POLICY_QMS_MODULE_STARTED || ViewBag.ErrorProof.BPolicyNm == Common.Constant.QmsConstant.POLICY_QMS_MODULE_REJECTED) && ViewBag.ErrorProof.ChargeUserOID == Convert.ToInt32(Session["UserOID"]))
                {
                    <table class="tableTopButtonBox">
                        <tbody>
                            <tr>
                                <td style="text-align: right;" id="InfoErrorProof_defaultBtn_@ViewBag.ErrorProof.OID">
                                    <button id="InfoErrorProof_EditBtn_@ViewBag.ErrorProof.OID" class="custom-button"><i class="fas fa-edit"></i> 수정</button>
                                    @*<button id="InfoErrorProof_AppDrwEditBtn_@ViewBag.QuickDetail.OID" class="custom-button"><i class="fas fa-highlighter"></i>문서 정정</button>*@
                                    <button id="InfoErrorProof_EditCancleBtn_@ViewBag.ErrorProof.OID" class="custom-button" style="display:none;"><i class="fas fa-times"></i> 취소</button>
                                    <button id="InfoErrorProof_SaveBtn_@ViewBag.ErrorProof.OID" class="custom-button" style="display:none;"><i class="fas fa-save"></i> 저장</button>
                                    <button id="InfoErrorProof_ApprovalBtn_@ViewBag.ErrorProof.OID" class="custom-button"><i class="fas fa-pen-alt"></i> 결재</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }

                <table width="100%" class="infoTable" style="table-layout:fixed;">
                    <colgroup>
                        <col style="width:180px;" />
                        <col style="width:auto;" />
                        <col style="width:180px;" />
                        <col style="width:auto;" />
                    </colgroup>
                    <tr>
                        <th>예정일자</th>
                        <td>
                            <div id="dtDlgEditErrorProofEstDt_@ViewBag.ErrorProof.OID" class="Modifiable_@ViewBag.ErrorProof.OID" AttrType="DATE" readonly="readonly"></div>
                        </td>
                        <th>처리일자</th>
                        <td>
                            <div id="dtDlgEditErrorProofActDt_@ViewBag.ErrorProof.OID" class="Modifiable_@ViewBag.ErrorProof.OID" AttrType="DATE" readonly="readonly"></div>
                        </td>
                    </tr>
                    <tr>
                        <th>점검내용</th>
                        <td colspan="3">
                            <input type="text" id="txtDlgEditErrorProofCheck_@ViewBag.ErrorProof.OID" class="Modifiable_@ViewBag.ErrorProof.OID" AttrType="TEXT" readonly="readonly" style="width:100%" value="@ViewBag.ErrorProof.CheckDetail" />
                        </td>
                    </tr>
                    <tr>
                        <th>점검 담당자</th>
                        <td colspan="3">
                            <div style="display:flex;">
                                <input type="text" id="txtDlgEditErrorProofCheckUser_@ViewBag.ErrorProof.OID" style="width:120px; margin-right:5px;" readonly="readonly" CheckUserOID="@ViewBag.ErrorProof.CheckUserOID" value="@ViewBag.ErrorProof.CheckUserNm" />
                                <button id="btnDlgEditErrorProofCheckUser_@ViewBag.ErrorProof.OID" class="Modifiable_@ViewBag.ErrorProof.OID" AttrType="BUTTON" style="display:none;"><i class="fas fa-search"></i> 검색</button>
                            </div>
                        </td>
                    </tr>
                </table>


                <label style="margin-top:20px;"><i class="fas fa-caret-square-down"></i> 첨부파일</label>
                <div id="InfoErrorProof_FileList_@ViewBag.ErrorProof.OID">

                </div>
            </div>
            <div id="Apphis" class="basic_grid dective">
                <div id="ApphisInfo_@ViewBag.ErrorProof.OID">
                </div>
            </div>
            <div id="Downhis" class="basic_grid dective">
                @{Html.RenderAction("FileHistory", "Common", new { OID = ViewBag.ErrorProof.OID });}
            </div>
        </div>
    </div>

<script type="text/javascript">
    $(document).ready(function () {
        const ErrorProofOID = '@ViewBag.ErrorProof.OID';
        var fileUpload = $("#InfoErrorProof_FileList_" + ErrorProofOID).FileUpload({ OID: ErrorProofOID });

        const ErrorProofDiv$ = $('#InfoErrorProof_' + ErrorProofOID);
        $('#InfoErrorProof_' + ErrorProofOID + ' .tab').on('click', function () {
            const self$ = $(this);
            const infoValue = self$.attr('info');
            //control side menu
            ErrorProofDiv$.find('[class="tab info_focus"]').removeClass('info_focus');
            self$.addClass('info_focus');
            ErrorProofDiv$.find('[class="basic_grid"]').addClass('dective');
            ErrorProofDiv$.find('[id="' + infoValue + '"]').removeClass('dective');

            if (infoValue == 'properties') {

            } else if (infoValue == 'Apphis') {
                RequestHtml('/Common/ApprovalHistory', { OID: ErrorProofOID }, function (res) {
                    $('#ApphisInfo_' + ErrorProofOID).html(res);
                });
            }
        });

        $('#InfoErrorProof_EditBtn_' + ErrorProofOID).on('click', function () {
            var ModifyAttr = $('.Modifiable_' + ErrorProofOID);

            ModifyAttr.each(function (i, v) {
                ContentEditMode(v);  
            });

            //수정 가능한 항목을 표시
            var modifyTag = document.createElement('div');
            modifyTag.className = "modifyTag";

            $('.Modifiable_' + ErrorProofOID).parent().css('position', 'relative');

            $('.Modifiable_' + ErrorProofOID).parent().append(modifyTag);

            $("#InfoErrorProof_EditBtn_" + ErrorProofOID).css("display", "none");            
            $("#InfoErrorProof_SaveBtn_" + ErrorProofOID).css("display", "inline-block");
            $("#InfoErrorProof_EditCancleBtn_" + ErrorProofOID).css("display", "inline-block");  

            fileUpload.EditMode();
        });

        //$("#InfoErrorProof_EditCancleBtn_" + ErrorProofOID).jqxButton();
        $("#InfoErrorProof_EditCancleBtn_" + ErrorProofOID).on("click", function () {
            var ModifyAttr = $('.Modifiable_' + ErrorProofOID);

            ModifyAttr.each(function (i, v) {
                ContentReadMode(v);             
            });

            $(".modifyTag").remove();
            $("#InfoErrorProof_EditBtn_" + ErrorProofOID).css("display", "inline-block");  
            $("#InfoErrorProof_SaveBtn_" + ErrorProofOID).css("display", "none");
            $("#InfoErrorProof_EditCancleBtn_" + ErrorProofOID).css("display", "none");      

            fileUpload.ReadOnlyMode();
        });

        //$("#InfoErrorProof_SaveBtn_" + ErrorProofOID).jqxButton();
        $("#InfoErrorProof_SaveBtn_" + ErrorProofOID).on("click", function () {
            var param = {};
            param.OID = ErrorProofOID;
            param.ModuleOID = ErrorProofOID;
            param.EstDt = $("#dtDlgEditErrorProofEstDt_" + ErrorProofOID).val();
            param.ActDt = $("#dtDlgEditErrorProofActDt_" + ErrorProofOID).val();
            param.CheckDetail = $("#txtDlgEditErrorProofCheck_" + ErrorProofOID).val();
            param.CheckUserOID = $("#txtDlgEditErrorProofCheckUser_" + ErrorProofOID).attr("CheckUserOID");

            if (WebUtils.isEmpty(param.EstDt)) {
                alert("예정일자가 입력되지 않았습니다.");
                return;
            }

            if (WebUtils.isEmpty(param.ActDt)) {
                alert("처리일자가 입력되지 않았습니다.");
                return;
            }

            if (WebUtils.isEmpty(param.CheckDetail)) {
                alert("처리내용을 입력 해주세요.");
                return;
            }

            if (WebUtils.isEmpty(param.CheckUserOID)) {
                alert("점검담당자를 선택 해주세요.");
                return;
            }

            var Files = fileUpload.Files();

            var removeFiles = fileUpload.RemoveFiles();
            if (!WebUtils.isEmpty(removeFiles)) {
                param.delFiles = [];
                param.delFiles = removeFiles;
            }

           SendDataWithFile('/Qms/SaveQuickErrorProof', param, Files, function (response) {
                if (response.isError) {
                    alert(response.resultMessage);
                    return;
                }
               alert("저장되었습니다.");
               PageReload();
            }).fail(function (err) {
                alert(err.responseText);
            });
        });

        $("#InfoErrorProof_ApprovalBtn_" + ErrorProofOID).on("click", function () {
            var EstDt = $("#dtDlgEditErrorProofEstDt_" + ErrorProofOID).val();
            var ActDt = $("#dtDlgEditErrorProofActDt_" + ErrorProofOID).val();
            var CheckDetail = $("#txtDlgEditErrorProofCheck_" + ErrorProofOID).val();
            var CheckUserOID = $("#txtDlgEditErrorProofCheckUser_" + ErrorProofOID).attr("CheckUserOID");

            if (WebUtils.isEmpty(EstDt)) {
                alert("예정일자가 입력되지 않았습니다.");
                return;
            }

            if (WebUtils.isEmpty(ActDt)) {
                alert("처리일자가 입력되지 않았습니다.");
                return;
            }

            if (WebUtils.isEmpty(CheckDetail)) {
                alert("처리내용을 입력 해주세요.");
                return;
            }
            
            if (WebUtils.isEmpty(CheckUserOID)) {
                alert("점검담당자를 선택 해주세요.");
                return;
            }

            OpenApprovalDialog(function () {
                PageReload();
            }, null, { TargetOID: ErrorProofOID }, '/Common/Approval', '결재');
        });

        var dtDlgEditErrorProofEstDt$ = $("#dtDlgEditErrorProofEstDt_" + ErrorProofOID);
        var dtDlgEditErrorProofActDt$ = $("#dtDlgEditErrorProofActDt_" + ErrorProofOID);

        // 예정일자
        dtDlgEditErrorProofEstDt$.jqxDateTimeInput(DateFormat);
        dtDlgEditErrorProofEstDt$.jqxDateTimeInput({
            width: 150,
            height: 32,
            theme: "Light",
            disabled: true
        });

        var vEstDt = "@(ViewBag.ErrorProof.EstDt == null ? null : ViewBag.ErrorProof.EstDt.ToString("yyyy-MM-dd"))";
        dtDlgEditErrorProofEstDt$.val( vEstDt === null ? WebUtils.GetDate(-1, "m", "-") : vEstDt);
        // 처리일자
        dtDlgEditErrorProofActDt$.jqxDateTimeInput(DateFormat);
        dtDlgEditErrorProofActDt$.jqxDateTimeInput({
            width: 150,
            height: 32,
            theme: "Light",
            disabled: true
        });
        var vActDt = "@(ViewBag.ErrorProof.ActDt == null ? null : ViewBag.ErrorProof.ActDt.ToString("yyyy-MM-dd"))";
        dtDlgEditErrorProofActDt$.val( vActDt === null ? WebUtils.GetDate(-1, "m", "-") : vActDt);

        // 담당자 검색
        var btnDlgUserSearch$ = $("#btnDlgEditErrorProofCheckUser_" + ErrorProofOID).jqxButton();
        btnDlgUserSearch$.on("click", function () {
            OpenApprovalPersonDialog(function (res) {
                if (res.length > 1) {
                    alert("담당자는 한명만 지정 할 수 있습니다.");
                    return;
                }

                $("#txtDlgEditErrorProofCheckUser_" + ErrorProofOID).val(res[0].Name);
                $("#txtDlgEditErrorProofCheckUser_" + ErrorProofOID).attr("CheckUserOID", res[0].OID);

            }, null, null, '/Common/ApprovalPerson', '사용자 검색');
        });


    });
</script>